spark:
  appName: SparkStreamingLogAggregationApp
  duration: 2000
  pathToMlibModel: tmp/fp/ml
kafkaConnection:
  group: test
  topics:
    logs-topic: 1
  zookeeper: sandbox.hortonworks.com:2181
hbase:
  tableName: LOG_TABLEF3
  columnFamily: DATA
  zookeeperClientPort: 2181
  zookeeperQuorum: sandbox.hortonworks.com
  zookeeperParent: /hbase-unsecure
hadoop:
  fileSystem: hdfs://sandbox.hortonworks.com:8020/
  cityDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/dictionaries/cities.txt
  tagsDictionary: hdfs://sandbox.hortonworks.com:8020/tmp/dictionaries/tags.txt
elasticSearch:
  index: logs03
  type: logs


